services:

  mysql:
    image: mysql:8.4
    container_name: digital-banking-mysql
    environment:
      MYSQL_DATABASE: digital_banking_portal
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digital-banking-app
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/digital_banking_portal
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: