apiVersion: v1
kind: Service

metadata:
  name: digital-banking-portal

spec:
  type: NodePort

  selector:
    app: digital-banking-portal

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
